In [1]:
import pandas as pd

file = r"2024-10-08_to_2024-10-13_UI_202403B0923.xlsx"

xls = pd.ExcelFile(file)

print(xls.sheet_names)

['Gesamt-Kfz', 'SV >3.5t', 'LV <3.5t', 'Pkw', 'Pkw mit Anhänger', 'Lkw', 'Lkw mit Anhänger', 'Bus', 'Lieferwagen', 'Kraftrad', 'Sattel-Kfz', 'Erklärungen']

In [2]:
for sheet in xls.sheet_names:

    print("="*100)
    print(sheet)

    df = pd.read_excel(file, sheet_name=sheet, header=None)

    display(df.head(25))

====================================================================================================
Gesamt-Kfz

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,Name der Erhebung,NaN,UI_202403B0923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Geräte-UUID(s),NaN,d440422d-f10c-4884-905e-cc168d263334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Zähldatum,NaN,"Tue, 08. Oct 2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,von,nach,Wert,Spitzenzeit von Gesamt-Kfz,NaN,NaN,NaN,NaN
3,Startzeit,NaN,00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Tagesspitze,00:00:00,23:59:59,0,0,NaN,NaN,NaN,NaN
4,Standort,NaN,"(50.127,8.689)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Morgenspitze,06:00:00,10:00:00,0,0,NaN,NaN,NaN,NaN
5,Gesamt-Kfz,NaN,"Pkw, Pkw mit Anhänger, Kraftrad, Lieferwagen, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Abendspitze,15:00:00,19:00:00,0,0,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Tagesverkehr,06:00:00,22:00:00,0,0,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Nachtverkehr,22:00:00,06:00:00,0,0,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,von Unten,von Links,NaN,von Oben,NaN,NaN,NaN,NaN,NaN,...,NaN,Unten,NaN,NaN,Links,NaN,NaN,Oben,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Startzeit,von Unten nach Oben,von Links nach Oben,von Links nach Unten,von Oben nach Unten,NaN,NaN,Intervall,Summe Stunde,NaN,...,NaN,Fahrtrichtung Süd-West,Fahrtrichtung Nord-Ost,Q,Fahrtrichtung Nord-West,Fahrtrichtung Süd-Ost,Q,Fahrtrichtung Nord-Ost,Fahrtrichtung Süd-West,Q
12,00:00:00,4,0,1,6,NaN,NaN,11,0,NaN,...,NaN,4,7,0,1,0,0,6,4,0
13,00:15:00,2,0,1,3,NaN,NaN,6,0,NaN,...,NaN,2,4,0,1,0,0,3,2,0
14,00:30:00,1,0,2,3,NaN,NaN,6,0,NaN,...,NaN,1,5,0,2,0,0,3,1,0
15,00:45:00,3,0,1,3,NaN,NaN,7,0,NaN,...,NaN,3,4,0,1,0,0,3,3,0
16,01:00:00,4,1,0,0,NaN,NaN,5,0,NaN,...,NaN,4,0,0,1,0,0,0,5,0
17,01:15:00,3,0,1,3,NaN,NaN,7,0,NaN,...,NaN,3,4,0,1,0,0,3,3,0
18,01:30:00,1,0,1,1,NaN,NaN,3,0,NaN,...,NaN,1,2,0,1,0,0,1,1,0
19,01:45:00,6,0,0,1,NaN,NaN,7,0,NaN,...,NaN,6,1,0,0,0,0,1,6,0
20,02:00:00,4,0,0,1,NaN,NaN,5,0,NaN,...,NaN,4,1,0,0,0,0,1,4,0
21,02:15:00,0,0,0,6,NaN,NaN,6,0,NaN,...,NaN,0,6,0,0,0,0,6,0,0
22,02:30:00,3,0,1,0,NaN,NaN,4,0,NaN,...,NaN,3,1,0,1,0,0,0,3,0
23,02:45:00,3,0,0,0,NaN,NaN,3,0,NaN,...,NaN,3,0,0,0,0,0,0,3,0
24,03:00:00,1,0,0,3,NaN,NaN,4,0,NaN,...,NaN,1,3,0,0,0,0,3,1,0

====================================================================================================
SV >3.5t

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,Name der Erhebung,NaN,UI_202403B0923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Geräte-UUID(s),NaN,d440422d-f10c-4884-905e-cc168d263334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Zähldatum,NaN,"Tue, 08. Oct 2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,von,nach,Wert,Spitzenzeit von SV >3.5t,NaN,NaN,NaN,NaN
3,Startzeit,NaN,00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Tagesspitze,00:00:00,23:59:59,0,0,NaN,NaN,NaN,NaN
4,Standort,NaN,"(50.127,8.689)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Morgenspitze,06:00:00,10:00:00,0,0,NaN,NaN,NaN,NaN
5,"SV >3,5t",NaN,"Lkw, Lkw mit Anhänger, Sattel-Kfz, Bus",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Abendspitze,15:00:00,19:00:00,0,0,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Tagesverkehr,06:00:00,22:00:00,0,0,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Nachtverkehr,22:00:00,06:00:00,0,0,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,von Unten,von Links,NaN,von Oben,NaN,NaN,NaN,NaN,NaN,...,NaN,Unten,NaN,NaN,Links,NaN,NaN,Oben,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Startzeit,von Unten nach Oben,von Links nach Oben,von Links nach Unten,von Oben nach Unten,NaN,NaN,Intervall,Summe Stunde,NaN,...,NaN,Fahrtrichtung Süd-West,Fahrtrichtung Nord-Ost,Q,Fahrtrichtung Nord-West,Fahrtrichtung Süd-Ost,Q,Fahrtrichtung Nord-Ost,Fahrtrichtung Süd-West,Q
12,00:00:00,1,0,0,0,NaN,NaN,1,0,NaN,...,NaN,1,0,0,0,0,0,0,1,0
13,00:15:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
14,00:30:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
15,00:45:00,1,0,0,0,NaN,NaN,1,0,NaN,...,NaN,1,0,0,0,0,0,0,1,0
16,01:00:00,2,0,0,0,NaN,NaN,2,0,NaN,...,NaN,2,0,0,0,0,0,0,2,0
17,01:15:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
18,01:30:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
19,01:45:00,5,0,0,0,NaN,NaN,5,0,NaN,...,NaN,5,0,0,0,0,0,0,5,0
20,02:00:00,1,0,0,0,NaN,NaN,1,0,NaN,...,NaN,1,0,0,0,0,0,0,1,0
21,02:15:00,0,0,0,1,NaN,NaN,1,0,NaN,...,NaN,0,1,0,0,0,0,1,0,0
22,02:30:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
23,02:45:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
24,03:00:00,0,0,0,1,NaN,NaN,1,0,NaN,...,NaN,0,1,0,0,0,0,1,0,0

====================================================================================================
LV <3.5t

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,Name der Erhebung,NaN,UI_202403B0923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Geräte-UUID(s),NaN,d440422d-f10c-4884-905e-cc168d263334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Zähldatum,NaN,"Tue, 08. Oct 2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,von,nach,Wert,Spitzenzeit von LV <3.5t,NaN,NaN,NaN,NaN
3,Startzeit,NaN,00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Tagesspitze,00:00:00,23:59:59,0,0,NaN,NaN,NaN,NaN
4,Standort,NaN,"(50.127,8.689)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Morgenspitze,06:00:00,10:00:00,0,0,NaN,NaN,NaN,NaN
5,"LV <3,5t",NaN,"Pkw, Pkw mit Anhänger, Kraftrad, Lieferwagen",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Abendspitze,15:00:00,19:00:00,0,0,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Tagesverkehr,06:00:00,22:00:00,0,0,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Nachtverkehr,22:00:00,06:00:00,0,0,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,von Unten,von Links,NaN,von Oben,NaN,NaN,NaN,NaN,NaN,...,NaN,Unten,NaN,NaN,Links,NaN,NaN,Oben,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Startzeit,von Unten nach Oben,von Links nach Oben,von Links nach Unten,von Oben nach Unten,NaN,NaN,Intervall,Summe Stunde,NaN,...,NaN,Fahrtrichtung Süd-West,Fahrtrichtung Nord-Ost,Q,Fahrtrichtung Nord-West,Fahrtrichtung Süd-Ost,Q,Fahrtrichtung Nord-Ost,Fahrtrichtung Süd-West,Q
12,00:00:00,3,0,1,6,NaN,NaN,10,0,NaN,...,NaN,3,7,0,1,0,0,6,3,0
13,00:15:00,2,0,1,3,NaN,NaN,6,0,NaN,...,NaN,2,4,0,1,0,0,3,2,0
14,00:30:00,1,0,2,3,NaN,NaN,6,0,NaN,...,NaN,1,5,0,2,0,0,3,1,0
15,00:45:00,2,0,1,3,NaN,NaN,6,0,NaN,...,NaN,2,4,0,1,0,0,3,2,0
16,01:00:00,2,1,0,0,NaN,NaN,3,0,NaN,...,NaN,2,0,0,1,0,0,0,3,0
17,01:15:00,3,0,1,3,NaN,NaN,7,0,NaN,...,NaN,3,4,0,1,0,0,3,3,0
18,01:30:00,1,0,1,1,NaN,NaN,3,0,NaN,...,NaN,1,2,0,1,0,0,1,1,0
19,01:45:00,1,0,0,1,NaN,NaN,2,0,NaN,...,NaN,1,1,0,0,0,0,1,1,0
20,02:00:00,3,0,0,1,NaN,NaN,4,0,NaN,...,NaN,3,1,0,0,0,0,1,3,0
21,02:15:00,0,0,0,5,NaN,NaN,5,0,NaN,...,NaN,0,5,0,0,0,0,5,0,0
22,02:30:00,3,0,1,0,NaN,NaN,4,0,NaN,...,NaN,3,1,0,1,0,0,0,3,0
23,02:45:00,3,0,0,0,NaN,NaN,3,0,NaN,...,NaN,3,0,0,0,0,0,0,3,0
24,03:00:00,1,0,0,2,NaN,NaN,3,0,NaN,...,NaN,1,2,0,0,0,0,2,1,0

====================================================================================================
Pkw

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,Name der Erhebung,NaN,UI_202403B0923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Geräte-UUID(s),NaN,d440422d-f10c-4884-905e-cc168d263334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Zähldatum,NaN,"Tue, 08. Oct 2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,von,nach,Wert,Spitzenzeit von Pkw,NaN,NaN,NaN,NaN
3,Startzeit,NaN,00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Tagesspitze,00:00:00,23:59:59,0,0,NaN,NaN,NaN,NaN
4,Standort,NaN,"(50.127,8.689)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Morgenspitze,06:00:00,10:00:00,0,0,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Abendspitze,15:00:00,19:00:00,0,0,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Tagesverkehr,06:00:00,22:00:00,0,0,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Nachtverkehr,22:00:00,06:00:00,0,0,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,von Unten,von Links,NaN,von Oben,NaN,NaN,NaN,NaN,NaN,...,NaN,Unten,NaN,NaN,Links,NaN,NaN,Oben,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Startzeit,von Unten nach Oben,von Links nach Oben,von Links nach Unten,von Oben nach Unten,NaN,NaN,Intervall,Summe Stunde,NaN,...,NaN,Fahrtrichtung Süd-West,Fahrtrichtung Nord-Ost,Q,Fahrtrichtung Nord-West,Fahrtrichtung Süd-Ost,Q,Fahrtrichtung Nord-Ost,Fahrtrichtung Süd-West,Q
12,00:00:00,3,0,1,6,NaN,NaN,10,0,NaN,...,NaN,3,7,0,1,0,0,6,3,0
13,00:15:00,2,0,1,3,NaN,NaN,6,0,NaN,...,NaN,2,4,0,1,0,0,3,2,0
14,00:30:00,1,0,2,2,NaN,NaN,5,0,NaN,...,NaN,1,4,0,2,0,0,2,1,0
15,00:45:00,2,0,1,2,NaN,NaN,5,0,NaN,...,NaN,2,3,0,1,0,0,2,2,0
16,01:00:00,2,1,0,0,NaN,NaN,3,0,NaN,...,NaN,2,0,0,1,0,0,0,3,0
17,01:15:00,3,0,1,3,NaN,NaN,7,0,NaN,...,NaN,3,4,0,1,0,0,3,3,0
18,01:30:00,1,0,1,1,NaN,NaN,3,0,NaN,...,NaN,1,2,0,1,0,0,1,1,0
19,01:45:00,1,0,0,1,NaN,NaN,2,0,NaN,...,NaN,1,1,0,0,0,0,1,1,0
20,02:00:00,2,0,0,0,NaN,NaN,2,0,NaN,...,NaN,2,0,0,0,0,0,0,2,0
21,02:15:00,0,0,0,4,NaN,NaN,4,0,NaN,...,NaN,0,4,0,0,0,0,4,0,0
22,02:30:00,3,0,1,0,NaN,NaN,4,0,NaN,...,NaN,3,1,0,1,0,0,0,3,0
23,02:45:00,3,0,0,0,NaN,NaN,3,0,NaN,...,NaN,3,0,0,0,0,0,0,3,0
24,03:00:00,1,0,0,2,NaN,NaN,3,0,NaN,...,NaN,1,2,0,0,0,0,2,1,0

====================================================================================================
Pkw mit Anhänger

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,Name der Erhebung,NaN,UI_202403B0923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Geräte-UUID(s),NaN,d440422d-f10c-4884-905e-cc168d263334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Zähldatum,NaN,"Tue, 08. Oct 2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,von,nach,Wert,Spitzenzeit von Pkw mit Anhänger,NaN,NaN,NaN,NaN
3,Startzeit,NaN,00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Tagesspitze,00:00:00,23:59:59,0,0,NaN,NaN,NaN,NaN
4,Standort,NaN,"(50.127,8.689)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Morgenspitze,06:00:00,10:00:00,0,0,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Abendspitze,15:00:00,19:00:00,0,0,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Tagesverkehr,06:00:00,22:00:00,0,0,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Nachtverkehr,22:00:00,06:00:00,0,0,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,von Unten,von Links,NaN,von Oben,NaN,NaN,NaN,NaN,NaN,...,NaN,Unten,NaN,NaN,Links,NaN,NaN,Oben,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Startzeit,von Unten nach Oben,von Links nach Oben,von Links nach Unten,von Oben nach Unten,NaN,NaN,Intervall,Summe Stunde,NaN,...,NaN,Fahrtrichtung Süd-West,Fahrtrichtung Nord-Ost,Q,Fahrtrichtung Nord-West,Fahrtrichtung Süd-Ost,Q,Fahrtrichtung Nord-Ost,Fahrtrichtung Süd-West,Q
12,00:00:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
13,00:15:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
14,00:30:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
15,00:45:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
16,01:00:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
17,01:15:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
18,01:30:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
19,01:45:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
20,02:00:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
21,02:15:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
22,02:30:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
23,02:45:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
24,03:00:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0

====================================================================================================
Lkw

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,Name der Erhebung,NaN,UI_202403B0923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Geräte-UUID(s),NaN,d440422d-f10c-4884-905e-cc168d263334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Zähldatum,NaN,"Tue, 08. Oct 2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,von,nach,Wert,Spitzenzeit von Lkw,NaN,NaN,NaN,NaN
3,Startzeit,NaN,00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Tagesspitze,00:00:00,23:59:59,0,0,NaN,NaN,NaN,NaN
4,Standort,NaN,"(50.127,8.689)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Morgenspitze,06:00:00,10:00:00,0,0,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Abendspitze,15:00:00,19:00:00,0,0,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Tagesverkehr,06:00:00,22:00:00,0,0,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Nachtverkehr,22:00:00,06:00:00,0,0,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,von Unten,von Links,NaN,von Oben,NaN,NaN,NaN,NaN,NaN,...,NaN,Unten,NaN,NaN,Links,NaN,NaN,Oben,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Startzeit,von Unten nach Oben,von Links nach Oben,von Links nach Unten,von Oben nach Unten,NaN,NaN,Intervall,Summe Stunde,NaN,...,NaN,Fahrtrichtung Süd-West,Fahrtrichtung Nord-Ost,Q,Fahrtrichtung Nord-West,Fahrtrichtung Süd-Ost,Q,Fahrtrichtung Nord-Ost,Fahrtrichtung Süd-West,Q
12,00:00:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
13,00:15:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
14,00:30:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
15,00:45:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
16,01:00:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
17,01:15:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
18,01:30:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
19,01:45:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
20,02:00:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
21,02:15:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
22,02:30:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
23,02:45:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
24,03:00:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0

====================================================================================================
Lkw mit Anhänger

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,Name der Erhebung,NaN,UI_202403B0923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Geräte-UUID(s),NaN,d440422d-f10c-4884-905e-cc168d263334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Zähldatum,NaN,"Tue, 08. Oct 2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,von,nach,Wert,Spitzenzeit von Lkw mit Anhänger,NaN,NaN,NaN,NaN
3,Startzeit,NaN,00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Tagesspitze,00:00:00,23:59:59,0,0,NaN,NaN,NaN,NaN
4,Standort,NaN,"(50.127,8.689)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Morgenspitze,06:00:00,10:00:00,0,0,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Abendspitze,15:00:00,19:00:00,0,0,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Tagesverkehr,06:00:00,22:00:00,0,0,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Nachtverkehr,22:00:00,06:00:00,0,0,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,von Unten,von Links,NaN,von Oben,NaN,NaN,NaN,NaN,NaN,...,NaN,Unten,NaN,NaN,Links,NaN,NaN,Oben,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Startzeit,von Unten nach Oben,von Links nach Oben,von Links nach Unten,von Oben nach Unten,NaN,NaN,Intervall,Summe Stunde,NaN,...,NaN,Fahrtrichtung Süd-West,Fahrtrichtung Nord-Ost,Q,Fahrtrichtung Nord-West,Fahrtrichtung Süd-Ost,Q,Fahrtrichtung Nord-Ost,Fahrtrichtung Süd-West,Q
12,00:00:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
13,00:15:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
14,00:30:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
15,00:45:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
16,01:00:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
17,01:15:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
18,01:30:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
19,01:45:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
20,02:00:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
21,02:15:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
22,02:30:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
23,02:45:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
24,03:00:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0

====================================================================================================
Bus

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,Name der Erhebung,NaN,UI_202403B0923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Geräte-UUID(s),NaN,d440422d-f10c-4884-905e-cc168d263334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Zähldatum,NaN,"Tue, 08. Oct 2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,von,nach,Wert,Spitzenzeit von Bus,NaN,NaN,NaN,NaN
3,Startzeit,NaN,00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Tagesspitze,00:00:00,23:59:59,0,0,NaN,NaN,NaN,NaN
4,Standort,NaN,"(50.127,8.689)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Morgenspitze,06:00:00,10:00:00,0,0,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Abendspitze,15:00:00,19:00:00,0,0,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Tagesverkehr,06:00:00,22:00:00,0,0,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Nachtverkehr,22:00:00,06:00:00,0,0,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,von Unten,von Links,NaN,von Oben,NaN,NaN,NaN,NaN,NaN,...,NaN,Unten,NaN,NaN,Links,NaN,NaN,Oben,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Startzeit,von Unten nach Oben,von Links nach Oben,von Links nach Unten,von Oben nach Unten,NaN,NaN,Intervall,Summe Stunde,NaN,...,NaN,Fahrtrichtung Süd-West,Fahrtrichtung Nord-Ost,Q,Fahrtrichtung Nord-West,Fahrtrichtung Süd-Ost,Q,Fahrtrichtung Nord-Ost,Fahrtrichtung Süd-West,Q
12,00:00:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
13,00:15:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
14,00:30:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
15,00:45:00,1,0,0,0,NaN,NaN,1,0,NaN,...,NaN,1,0,0,0,0,0,0,1,0
16,01:00:00,2,0,0,0,NaN,NaN,2,0,NaN,...,NaN,2,0,0,0,0,0,0,2,0
17,01:15:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
18,01:30:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
19,01:45:00,5,0,0,0,NaN,NaN,5,0,NaN,...,NaN,5,0,0,0,0,0,0,5,0
20,02:00:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
21,02:15:00,0,0,0,1,NaN,NaN,1,0,NaN,...,NaN,0,1,0,0,0,0,1,0,0
22,02:30:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
23,02:45:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
24,03:00:00,0,0,0,1,NaN,NaN,1,0,NaN,...,NaN,0,1,0,0,0,0,1,0,0

====================================================================================================
Lieferwagen

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,Name der Erhebung,NaN,UI_202403B0923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Geräte-UUID(s),NaN,d440422d-f10c-4884-905e-cc168d263334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Zähldatum,NaN,"Tue, 08. Oct 2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,von,nach,Wert,Spitzenzeit von Lieferwagen,NaN,NaN,NaN,NaN
3,Startzeit,NaN,00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Tagesspitze,00:00:00,23:59:59,0,0,NaN,NaN,NaN,NaN
4,Standort,NaN,"(50.127,8.689)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Morgenspitze,06:00:00,10:00:00,0,0,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Abendspitze,15:00:00,19:00:00,0,0,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Tagesverkehr,06:00:00,22:00:00,0,0,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Nachtverkehr,22:00:00,06:00:00,0,0,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,von Unten,von Links,NaN,von Oben,NaN,NaN,NaN,NaN,NaN,...,NaN,Unten,NaN,NaN,Links,NaN,NaN,Oben,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Startzeit,von Unten nach Oben,von Links nach Oben,von Links nach Unten,von Oben nach Unten,NaN,NaN,Intervall,Summe Stunde,NaN,...,NaN,Fahrtrichtung Süd-West,Fahrtrichtung Nord-Ost,Q,Fahrtrichtung Nord-West,Fahrtrichtung Süd-Ost,Q,Fahrtrichtung Nord-Ost,Fahrtrichtung Süd-West,Q
12,00:00:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
13,00:15:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
14,00:30:00,0,0,0,1,NaN,NaN,1,0,NaN,...,NaN,0,1,0,0,0,0,1,0,0
15,00:45:00,0,0,0,1,NaN,NaN,1,0,NaN,...,NaN,0,1,0,0,0,0,1,0,0
16,01:00:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
17,01:15:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
18,01:30:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
19,01:45:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
20,02:00:00,1,0,0,1,NaN,NaN,2,0,NaN,...,NaN,1,1,0,0,0,0,1,1,0
21,02:15:00,0,0,0,1,NaN,NaN,1,0,NaN,...,NaN,0,1,0,0,0,0,1,0,0
22,02:30:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
23,02:45:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
24,03:00:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0

====================================================================================================
Kraftrad

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,Name der Erhebung,NaN,UI_202403B0923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Geräte-UUID(s),NaN,d440422d-f10c-4884-905e-cc168d263334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Zähldatum,NaN,"Tue, 08. Oct 2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,von,nach,Wert,Spitzenzeit von Kraftrad,NaN,NaN,NaN,NaN
3,Startzeit,NaN,00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Tagesspitze,00:00:00,23:59:59,0,0,NaN,NaN,NaN,NaN
4,Standort,NaN,"(50.127,8.689)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Morgenspitze,06:00:00,10:00:00,0,0,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Abendspitze,15:00:00,19:00:00,0,0,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Tagesverkehr,06:00:00,22:00:00,0,0,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Nachtverkehr,22:00:00,06:00:00,0,0,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,von Unten,von Links,NaN,von Oben,NaN,NaN,NaN,NaN,NaN,...,NaN,Unten,NaN,NaN,Links,NaN,NaN,Oben,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Startzeit,von Unten nach Oben,von Links nach Oben,von Links nach Unten,von Oben nach Unten,NaN,NaN,Intervall,Summe Stunde,NaN,...,NaN,Fahrtrichtung Süd-West,Fahrtrichtung Nord-Ost,Q,Fahrtrichtung Nord-West,Fahrtrichtung Süd-Ost,Q,Fahrtrichtung Nord-Ost,Fahrtrichtung Süd-West,Q
12,00:00:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
13,00:15:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
14,00:30:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
15,00:45:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
16,01:00:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
17,01:15:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
18,01:30:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
19,01:45:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
20,02:00:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
21,02:15:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
22,02:30:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
23,02:45:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
24,03:00:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0

====================================================================================================
Sattel-Kfz

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,Name der Erhebung,NaN,UI_202403B0923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Geräte-UUID(s),NaN,d440422d-f10c-4884-905e-cc168d263334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Zähldatum,NaN,"Tue, 08. Oct 2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,von,nach,Wert,Spitzenzeit von Sattel-Kfz,NaN,NaN,NaN,NaN
3,Startzeit,NaN,00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Tagesspitze,00:00:00,23:59:59,0,0,NaN,NaN,NaN,NaN
4,Standort,NaN,"(50.127,8.689)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Morgenspitze,06:00:00,10:00:00,0,0,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Abendspitze,15:00:00,19:00:00,0,0,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Tagesverkehr,06:00:00,22:00:00,0,0,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Nachtverkehr,22:00:00,06:00:00,0,0,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,von Unten,von Links,NaN,von Oben,NaN,NaN,NaN,NaN,NaN,...,NaN,Unten,NaN,NaN,Links,NaN,NaN,Oben,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Startzeit,von Unten nach Oben,von Links nach Oben,von Links nach Unten,von Oben nach Unten,NaN,NaN,Intervall,Summe Stunde,NaN,...,NaN,Fahrtrichtung Süd-West,Fahrtrichtung Nord-Ost,Q,Fahrtrichtung Nord-West,Fahrtrichtung Süd-Ost,Q,Fahrtrichtung Nord-Ost,Fahrtrichtung Süd-West,Q
12,00:00:00,1,0,0,0,NaN,NaN,1,0,NaN,...,NaN,1,0,0,0,0,0,0,1,0
13,00:15:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
14,00:30:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
15,00:45:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
16,01:00:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
17,01:15:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
18,01:30:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
19,01:45:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
20,02:00:00,1,0,0,0,NaN,NaN,1,0,NaN,...,NaN,1,0,0,0,0,0,0,1,0
21,02:15:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
22,02:30:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
23,02:45:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0
24,03:00:00,0,0,0,0,NaN,NaN,0,0,NaN,...,NaN,0,0,0,0,0,0,0,0,0

====================================================================================================
Erklärungen

,0,1,2
0,NaN,NaN,NaN
1,Bezeichnung,Zellen,Erklärung
2,Zufahrten,Zeile 10,Bezeichnungen der Knotenpunktarme/Zufahrten zu...
3,Abbieger/Wender,Zeile 12,Bezeichnungen der Abbiegeströme eines jeden Kn...
4,Startzeit,A13:A588,Uhrzeit ist Startzeit eines Intervalls z.B. 12...
5,NaN,Zeilen 13 bis 588,Gesamtfahrzeuge
6,Gesamt,Zeile 589,Summe des jeweiligen Abbiegestroms/24 h
7,Täglicher Spitzenwert,Zeilen 593 bis 594,Verkehrsreichste/höchste Spitzenstunde des vor...
8,Morgenspitze,Zeilen 596 bis 597,Erfasste Morgenspitzenstunde des vorliegenden ...
9,Abendspitze,Zeilen 599 bis 600,Erfasste Abendspitzenstunde des vorliegenden V...
10,Tagesverkehr,Zeilen 602 bis 603,Verkehrsreichste/höchste Spitzenstunde des vor...
11,Nachtverkehr,Zeilen 605 bis 606,Verkehrsreichste/höchste Spitzenstunde des vor...
12,NaN,NaN,NaN
13,Intervall,Spalte H,Summe aller am Knotenpunkt auftretenden Kfz in...
14,Summe Stunde,Spalte I,Summe aller am Knotenpunkt auftretenden Kfz de...
15,NaN,NaN,NaN
16,Tabelle zu den Spitzenstunden des Knotenpunktes,Zellen O3:S8,"Darstellung der Tages-, Morgen- und Abendspitz..."
17,NaN,NaN,NaN
18,Richtungsquerschnitt,Zellen O bis W,Darstellung der in den Knotenpunkt ein- und au...
19,NaN,NaN,NaN
20,Name,NaN,Erklärung
21,Gesamt-Kfz,NaN,alle am Knotenpunkt erfassten straßengebundene...
22,"SV >3,5t",NaN,gesamter am Knotenpunkt erfasster Schwerverkeh...
23,"LV <3,5t",NaN,gesamter am Knotenpunkt erfasster Leichtverkeh...

In [3]:
for sheet in xls.sheet_names:

    print(sheet)

    df = pd.read_excel(file, sheet_name=sheet, header=None)

    print(df.shape)

    print()

Gesamt-Kfz
(606, 23)

SV >3.5t
(606, 23)

LV <3.5t
(606, 23)

Pkw
(606, 23)

Pkw mit Anhänger
(606, 23)

Lkw
(606, 23)

Lkw mit Anhänger
(606, 23)

Bus
(606, 23)

Lieferwagen
(606, 23)

Kraftrad
(606, 23)

Sattel-Kfz
(606, 23)

Erklärungen
(24, 3)